### ISSUE TITLE
Missing room in LAN lobby

### ISSUE THREAD

**Issue by Aced14** [warhawkreborn/connector_windows#4]
Around 2 hours ago, I checked the [Warhawk Reborn (WR) site's status page](https://warhawk.thalhammer.it/status/) and saw the following rooms listed as open:
- [LGNS]Sapphire
- BigBlackBart

When I subsequently started the Windows version of WR and checked Warhawk's LAN lobby on my PS3, only [LGNS]Sapphire was listed. I'm used to pressing triangle to refresh the LAN lobby to work around issue #1, but refreshing didn't help this time around. Nothing changed no matter how much I refreshed.

I did notice that both rooms were shown as online in the Windows version's window. Just to see what would happen, I exited the Windows version of WR and launched the Android version. While using the Android version, both rooms appeared in Warhawk's LAN lobby and I was able to successfully join BigBlackBart.

Given that there are likely many Warhawk players out there that use the Windows version of WR, there could be value in updating it to resolve this kind of issue. Especially since there are usually only 1-2 active rooms open at any given time (not ideal if some players can't see them).

**Screenshots...**

[WR site's status page](https://warhawk.thalhammer.it/status/):
![warhawk-reborn-status-server-list](https://user-images.githubusercontent.com/13129485/82766875-b86bb600-9df0-11ea-91fd-4c92c6906c20.png)

Windows WR app's window:
![warhawk-reborn-windows-app](https://user-images.githubusercontent.com/13129485/82766844-6c207600-9df0-11ea-836a-1aa6e3b9e2be.png)

**Comment by DarrenKelley** [comment]
Same thing happen to 2 people using windows app today... They could not see me in ps3 lobby.. they hit triangle several times. Also my server kept disappearing from the broadcast. I even had my screen never sleep. I use the latest updates. I had to refresh "host server"
